### PR TITLE
Support Gzip Compression 

### PR DESCRIPTION
**Pull request by vaibhavepatel**
# Description
Compress the logs using Gzip prior to sending it over http to destination. 
- Reduces network bandwidth
- Smaller payloads sent over network, reduces network latency

Fixes # (issue)
Enhancement #166 

# Checklist
Work in progress

- [ ] I have squashed my commits into a single one with a message that aligns with the contributing guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by vaibhavepatel — COMMENTED** [review]
@FantasticFiasco Changes look great! I see what you meant by refactoring out the HTTP Client into it's own. If another application wants to implement their own version of HTTP Client for different encodings or something else they can. 

I also reviewed through all the changes you implemented and one thing stood out to me. I see that in the HTTP Clients you have the 'using' statements without the braces. I believe this is only [supported with C# 8.0](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using) and it is only available for [.NET Core 3.x and .NET Standard 2.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). This change means that you will no longer be supporting .NET Framework after this enhancement is released, correct?

**Comment by FantasticFiasco** [comment]
The `using` statement without braces is just C# 8 syntax sugar. If you look at the compiles code using a decompiler like [JetBrains dotPeek](https://www.jetbrains.com/decompiler/) you'll see that the actual code targeting .NET 4.5 looks something like this.

```csharp
public virtual async Task<HttpResponseMessage> PostAsync(string requestUri, Stream contentStream)
{
  HttpResponseMessage httpResponseMessage;
  using (StreamContent content = new StreamContent(contentStream))
  {
    content.Headers.Add("Content-Type", "application/json");
    httpResponseMessage = await this.httpClient.PostAsync(requestUri, (HttpContent) content).ConfigureAwait(false);
  }
  return httpResponseMessage;
}
```

I'll do a final review tonight and complement with some new tests cases if required, but I think we are ready for a new beta release after that. And you can try that release and see whether it works in your environment?

**Comment by vaibhavepatel** [comment]
Thanks for taking the time to go through it and explain. based on what you showed, it seems like it should be good the way it has been implemented.

Once again, thanks for getting this implemented so quickly! I will try and get this tested and provide you an update on the results. Note, I probably won't have the results until next week. 

I also want to clarify the behavior of how the Gzip implementation will work based on what we discussed and your implementation. The behavior of the Sinks will be the same, up till it is sent over Http. The BatchFormatter will be based on the uncompressed logs and the logs stored in memory or file will still be in an uncompressed state. Only when it gets to the GzipHttpClient will the logs be compressed. If it is using the JsonHttpClient, it will be sent over the network uncompressed. This means that payload created with the 'batchPostingLimit' and 'bufferFileSizeLimitBytes' configuration will be based on the uncompressed log(s), regardless of the HttpClient used.

**Comment by FantasticFiasco** [comment]
Good remarks!

I've added some more documentation to the sink parameter `batchSizeLimitBytes` as well as to the `JsonGzipHttpClient`. Do you think that is enough?

Given that you tell me it is, I'll create a new beta release for you to try out in your environment.

**Review by vaibhavepatel — COMMENTED** [review]
Looks good to me!

**Pull request merged**
