### PR TITLE
feat: add support for http basic authentication

### PR DESCRIPTION
**Pull request by peterhirn**
Added support for basic authentication. Could also be implemented as generic http header option, like https://github.com/serilog/serilog-sinks-elasticsearch/pull/90/commits/317ee59772fbf959b9efbf95d9c12fb4739c4c5e.

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Hi peterhirn and thanks for the PR!

- Is this to be thought of as a convenient way for initiating the HTTP sink with a client that authenticates with a log server using Basic authentication?
- Is the sink still configured in code, or using the `Serilog.Settings.Configuration` NuGet?

Sorry for the questions, I just want to understand the exact problem we are solving.

**Comment by peterhirn** [comment]
Hi! Thanks for your response.

> Is this to be thought of as a convenient way for initiating the HTTP sink with a client that authenticates with a log server using Basic authentication?

Exactly. I'm not familiar with `Serilog.Settings.Configuration` yet. Is there a way to get basic authentication working without my changes? If so, sorry for wasting your time.

**Comment by FantasticFiasco** [comment]
You are definitely not wasting my time, it is vital for me to understand your situation in order to solve your issue.

You ought to be able to do something like this with the latest official HTTP sink release:

```
class MyBasicAuthenticatedClient : HttpClient, IHttpClient
{
    public MyBasicAuthenticatedClient(string username, string password)
    {
        var credentials = Encoding.ASCII.GetBytes(user + ":" + password);
        DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(credentials));
    }
}
```

And then when you configure Serilog you write like this:

```
Serilog.ILogger log = new LoggerConfiguration()
    .WriteTo.Http("www.mylogs.com", new Options(), httpClient: new MyBasicAuthenticatedClient("john", "doe"))
    .CreateLogger();
```

Would that solve your problem?

**Comment by peterhirn** [comment]
Yes it absolutely does. Thank you very much! I failed to realize that I could pass in my own HttpClient.

**Comment by FantasticFiasco** [comment]
You are not completely wrong, I am starting to realize that the configuration you are performing wouldn't be possible in combination with `Serilog.Settings.Configuration`, that is something I need to think about.

**Pull request closed without merging**
