### PR TITLE
Add IBatchedTextFormatter interface to enable the customization of the format used to send data #16

### PR DESCRIPTION
**Pull request by FantasticFiasco**

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
I think I am done now. Do you have any other commits you would like to push?

If not, can you squash the commits into one, and I'll merge it to master.

**Comment by kvpt** [comment]
Everything is perfect for me, nothing to add.
I squashed all the related commits.

A big thank you for all your work.

**Comment by FantasticFiasco** [comment]
Would it be possible for you to verify that you with these changes are able to send log events to logz.io? Either reference the dll directly or if you want I'll build you a beta nuget.

**Comment by kvpt** [comment]
I implemented the BatchFormatter to send events to Logz.Io.
And I can confirm that it works fine in the Staging Environment.

**Pull request merged**
